CREATE TABLE "HR"."COUNTRIES_GDP" (
	"YEAR" VARCHAR2(400)
	,"GDP" NUMBER(20, 4)
	,"COUNTRY_NAME" VARCHAR2(400)
	,"COUNTRY_CODE" VARCHAR2(400)
	,"INDICATOR_NAME" VARCHAR2(400)
	,"INDICATOR_CODE" VARCHAR2(400)
	,PRIMARY KEY (
		"COUNTRY_CODE"
		,"YEAR"
		)
	);

CREATE UNIQUE INDEX "HR"."SYS_C007134" ON "HR"."COUNTRIES_GDP" (
	"COUNTRY_CODE"
	,"YEAR"
	);

CREATE TABLE "HR"."GDP_COUNTRY_REGION_LKP" (
	"COUNTRY_CODE" VARCHAR2(400)
	,"REGION" VARCHAR2(400)
	,"INCOME_GROUP" VARCHAR2(400)
	,"SPECIAL_NOTES" VARCHAR2(4000)
	,"TABLE_NAME" VARCHAR2(400)
	,PRIMARY KEY ("COUNTRY_CODE")
	);

CREATE UNIQUE INDEX "HR"."SYS_C007137" ON "HR"."GDP_COUNTRY_REGION_LKP" ("COUNTRY_CODE");

-- HR.OLYMPIC_RAW_HISTORY definition
CREATE TABLE "HR"."OLYMPIC_RAW_HISTORY" (
	"ID" VARCHAR2(40)
	,"NAME" VARCHAR2(400)
	,"SEX" VARCHAR2(40)
	,"AGE" VARCHAR2(40)
	,"HEIGHT" VARCHAR2(400)
	,"WEIGHT" VARCHAR2(400)
	,"TEAM" VARCHAR2(400)
	,"NOC" VARCHAR2(400)
	,"GAMES" VARCHAR2(400)
	,"YEAR" VARCHAR2(400)
	,"SEASON" VARCHAR2(400)
	,"CITY" VARCHAR2(400)
	,"SPORT" VARCHAR2(400)
	,"EVENT" VARCHAR2(400)
	,"MEDAL" VARCHAR2(400)
	);

-- HR.VW_OLYMPIC_DATA_HIST source
CREATE
	OR REPLACE VIEW HR.VW_OLYMPIC_DATA_HIST AS
SELECT NAME
	,SEX
	,TO_NUMBER(DECODE(AGE, 'NA', NULL, AGE)) AS AGE
	,TO_NUMBER(DECODE(HEIGHT, 'NA', NULL, HEIGHT)) AS HEIGHT_CM
	,TO_NUMBER(DECODE(WEIGHT, 'NA', NULL, WEIGHT)) AS WEIGHT_KG
	,TEAM
	,NOC
	,GAMES
	,YEAR
	,SEASON
	,CITY
	,SPORT
	,EVENT
	,DECODE(MEDAL, 'NA', NULL, MEDAL) AS MEDAL
FROM HR.OLYMPIC_RAW_HISTORY;

-- HR.VW_OLYMPIC_DATA_HIST_AGGR source
CREATE
	OR REPLACE VIEW HR.VW_OLYMPIC_DATA_HIST_AGGR AS
SELECT YEAR
	,GAMES
	,SEASON
	,AGE
	,TEAM AS COUNTRY_NAME
	,NOC AS COUNTRY_CODE
	,SEX
	,SPORT
	,EVENT
	,COUNT(1) AS PARTCIPANTS
	,COUNT(medal) AS MEDAL_TOTAL
	,COUNT(DECODE(MEDAL, 'Gold', MEDAL, NULL)) AS GOLD_MEDAL
	,COUNT(DECODE(MEDAL, 'Silver', MEDAL, NULL)) AS Silver_MEDAL
	,COUNT(DECODE(MEDAL, 'Bronze', MEDAL, NULL)) AS Bronze_MEDAL
FROM HR.VW_OLYMPIC_DATA_HIST
GROUP BY YEAR
	,GAMES
	,SEASON
	,AGE
	,TEAM
	,NOC
	,SEX
	,SPORT
	,EVENT;

CREATE
	OR REPLACE VIEW HR.VW_COUNTRIES_GDP_HIST AS
SELECT YEAR
	,TO_NUMBER(DECODE(GDP, 'NA', NULL, GDP)) AS GDP_USD
	,C.COUNTRY_NAME
	,C.COUNTRY_CODE
	,G.INCOME_GROUP
	,C.INDICATOR_NAME
	,C.INDICATOR_CODE
FROM HR.COUNTRIES_GDP C
LEFT JOIN HR.GDP_COUNTRY_REGION_LKP G ON C.COUNTRY_CODE = G.COUNTRY_CODE
WHERE G.REGION IS NOT NULL;
