CREATE TABLE "HR"."COUNTRIES_GDP" (
	"YEAR" VARCHAR2(400)
	,"GDP" NUMBER(20, 4)
	,"COUNTRY_NAME" VARCHAR2(400)
	,"COUNTRY_CODE" VARCHAR2(400)
	,"INDICATOR_NAME" VARCHAR2(400)
	,"INDICATOR_CODE" VARCHAR2(400)
	,PRIMARY KEY (
		"COUNTRY_CODE"
		,"YEAR"
		)
	);

CREATE UNIQUE INDEX "HR"."SYS_C007134" ON "HR"."COUNTRIES_GDP" (
	"COUNTRY_CODE"
	,"YEAR"
	);

CREATE TABLE "HR"."GDP_COUNTRY_REGION_LKP" (
	"COUNTRY_CODE" VARCHAR2(400)
	,"REGION" VARCHAR2(400)
	,"INCOME_GROUP" VARCHAR2(400)
	,"SPECIAL_NOTES" VARCHAR2(4000)
	,"TABLE_NAME" VARCHAR2(400)
	,PRIMARY KEY ("COUNTRY_CODE")
	);



-- HR.OLYMPIC_RAW_HISTORY definition
CREATE TABLE "HR"."OLYMPIC_RAW_HISTORY" (
	"ID" VARCHAR2(40)
	,"NAME" VARCHAR2(400)
	,"SEX" VARCHAR2(40)
	,"AGE" VARCHAR2(40)
	,"HEIGHT" VARCHAR2(400)
	,"WEIGHT" VARCHAR2(400)
	,"TEAM" VARCHAR2(400)
	,"NOC" VARCHAR2(400)
	,"GAMES" VARCHAR2(400)
	,"YEAR" VARCHAR2(400)
	,"SEASON" VARCHAR2(400)
	,"CITY" VARCHAR2(400)
	,"SPORT" VARCHAR2(400)
	,"EVENT" VARCHAR2(400)
	,"MEDAL" VARCHAR2(400)
	);
	
	
CREATE
	OR REPLACE VIEW HR.VW_OLYMPIC_DATA_HIST AS
SELECT HIST.NAME
	,HIST.SEX
	,TO_NUMBER(DECODE(HIST.AGE, 'NA', NULL, AGE)) AS AGE
	,TO_NUMBER(DECODE(HIST.HEIGHT, 'NA', NULL, HEIGHT)) AS HEIGHT_CM
	,TO_NUMBER(DECODE(HIST.WEIGHT, 'NA', NULL, WEIGHT)) AS WEIGHT_KG
	,TO_NUMBER(GD.GDP_USD) AS GDP_USD
	,TO_NUMBER(GD.GDP_PER_CAPITA_USD) AS GDP_PER_CAPITA_USD
	,gd.income_group
	,HIST.TEAM
	,HIST.NOC
	,HIST.GAMES
	,HIST.YEAR
	,HIST.SEASON
	,HIST.CITY
	,HIST.SPORT
	,HIST.EVENT
	,DECODE(HIST.MEDAL, 'NA', NULL, HIST.MEDAL) AS MEDAL
FROM HR.OLYMPIC_RAW_HISTORY HIST
LEFT JOIN HR.VW_COUNTRIES_GDP_HIST GD ON GD.COUNTRY_CODE = HIST.NOC
	AND GD."YEAR" = HIST."YEAR"

CREATE
	OR REPLACE VIEW HR.VW_OLYMPIC_DATA_HIST_AGGR AS
	WITH TEMP AS (
			SELECT O.NAME
				,O.YEAR
				,O.GAMES
				,O.SEASON
				,O.TEAM AS COUNTRY_NAME
				,O.NOC AS COUNTRY_CODE
				,G.INCOME_GROUP
				,O.SEX
				,O.SPORT
				,O.EVENT
				,CASE 
					WHEN O.MEDAL IS NOT NULL
						THEN O.YEAR || O.GAMES || O.NOC || O.EVENT || O.MEDAL
					ELSE NULL
					END AS UNIQUE_MEDAL_EVENT_COUNTRY
				,O.MEDAL
			FROM HR.VW_OLYMPIC_DATA_HIST O
			)

SELECT O.YEAR
	,O.GAMES
	,O.SEASON
	,O.COUNTRY_NAME
	,O.COUNTRY_CODE
	,G.INCOME_GROUP
	,O.SEX
	,O.SPORT
	,O.EVENT
	,COUNT(DISTINCT (O.NAME)) AS PARTCIPANTS
	,COUNT(DISTINCT (UNIQUE_MEDAL_EVENT_COUNTRY)) AS MEDAL_TOTAL
	,COUNT(DISTINCT (DECODE(O.MEDAL, 'Gold', O.UNIQUE_MEDAL_EVENT_COUNTRY, NULL))) AS GOLD_MEDAL
	,COUNT(DISTINCT (DECODE(O.MEDAL, 'Silver', O.UNIQUE_MEDAL_EVENT_COUNTRY, NULL))) AS Silver_MEDAL
	,COUNT(DISTINCT (DECODE(O.MEDAL, 'Bronze', O.UNIQUE_MEDAL_EVENT_COUNTRY, NULL))) AS Bronze_MEDAL
FROM TEMP O
LEFT JOIN HR.VW_COUNTRIES_GDP_HIST G ON O."YEAR" = G."YEAR"
	AND O.COUNTRY_CODE = G.COUNTRY_CODE
GROUP BY O.YEAR
	,O.GAMES
	,O.SEASON
	,O.COUNTRY_NAME
	,O.COUNTRY_CODE
	,G.INCOME_GROUP
	,O.SEX
	,O.SPORT
	,O.EVENT;



CREATE
	OR REPLACE VIEW HR.VW_COUNTRIES_GDP_HIST AS
SELECT GDP_OA.YEAR
	,TO_NUMBER(DECODE(GDP_OA.GDP, 'NA', NULL, GDP_OA.GDP)) AS GDP_USD
	,TO_NUMBER(DECODE(GDP_PC.GDP, 'NA', NULL, GDP_PC.GDP)) AS GDP_PER_CAPITA_USD
	,GDP_OA.COUNTRY_NAME
	,GDP_OA.COUNTRY_CODE
	,G.INCOME_GROUP
	,GDP_OA.INDICATOR_NAME
	,GDP_OA.INDICATOR_CODE
FROM HR.COUNTRIES_GDP GDP_OA
LEFT JOIN HR.COUNTRIES_GDP GDP_PC ON GDP_OA.YEAR = GDP_PC.YEAR
	AND GDP_OA.COUNTRY_CODE = GDP_PC.COUNTRY_CODE
	AND GDP_OA.INDICATOR_CODE = 'NY.GDP.MKTP.CD'
	AND GDP_PC.INDICATOR_CODE = 'NY.GDP.PCAP.CD'
LEFT JOIN HR.GDP_COUNTRY_REGION_LKP G ON GDP_OA.COUNTRY_CODE = G.COUNTRY_CODE
WHERE G.REGION IS NOT NULL
